name: node-code-pipeline
on: [push, workflow-dispatch]  
# even we can add multiple events to trigger this workflow like above 
jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
        - name: code checkout
          uses: actions/checkout@v3
        - name: install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Run Tests
          run: npm test
    # Adding another job under jobs , since test is one job we add deployment as another job
  Deploy:
    runs-on: ubuntu-latest
    # if we want to run this job after the first job is ran succesfuly we have to add below key word 
    needs: test-node
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
