name: actions test

on: [push]

jobs:
    testing-the-actions:
      runs-on: ubuntu-latest
      steps:
        - name: actions checkout
          uses: actions/checkout@v3
        - name: list the checkout files
          run: |
            pwd
            ls -la