name: gh-sample
on: #[push]
  #schedule:
  #  - cron: "* * * * *"
jobs:
    run-shell-commands:
      runs-on: ubuntu-latest 
      steps:
        - name: print
          run: echo "Hello Pradeep"
        - name: check multiple versions
          run: |
            mvn --version
            node -v 
            npm -v
        - name: python commands
          run: |
            import platform
            print(platform.processor())
          shell: python